# tasks file for ubuntu-1604-letsencrypt-apache
---
- name: configure | create http challenges directory
  file:
    path: "{{ ubuntu_1604_letsencrypt_apache_webroot_path }}/{{ ubuntu_1604_letsencrypt_apache_acme_challenge_path }}"
    state: directory

- name: configure | copy alias configuration file
  template:
    src: etc/apache2/conf-available/letsencrypt.conf.j2
    dest: "/etc/apache2/conf-available/letsencrypt.conf"
  register: _copy_alias_configuration_file

- name: configure | enable alias configuration
  command: a2enconf letsencrypt
  args:
    creates: "/etc/apache2/conf-enabled/letsencrypt.conf"
  register: _enable_alias_configuration

- name: configure | reload apache2
  service:
    name: apache2
    state: reloaded
  when: _copy_alias_configuration_file | changed or _enable_alias_configuration | changed

- name: configure | request host certificate
  command: "certbot-auto certonly -n --agree-tos --keep-until-expiring --expand --webroot -w {{ ubuntu_1604_letsencrypt_apache_webroot_path }} --cert-name {{ ansible_host }} -d {{ ansible_host }} --email {{ ubuntu_1604_letsencrypt_apache_admin_email }}"
  register: _ubuntu_1604_letsencrypt_configure_request_host_certificate
  changed_when: "not 'no action taken' in _ubuntu_1604_letsencrypt_configure_request_host_certificate.stdout"

- name: configure | request additional certificates
  command: "certbot-auto certonly -n --agree-tos --keep-until-expiring --expand --webroot -w {{ ubuntu_1604_letsencrypt_apache_webroot_path }} --cert-name {{ item.name }} -d {{ item.name }} {{ '-d' if (item.alias | default([]) | length > 0) else '' }} {{ item.alias | default([]) | join(' -d ') }}"
  register: _ubuntu_1604_letsencrypt_configure_request_additional_certificates
  changed_when: "not 'no action taken' in _ubuntu_1604_letsencrypt_configure_request_additional_certificates.stdout"
  with_items: "{{ ubuntu_1604_letsencrypt_apache_additional_certificates }}"

- name: configure | install cron job
  cron:
    name: letsencrypt auto renewal
    job: /usr/local/bin/certbot-auto renew --no-self-upgrade >> "/var/log/letsencrypt-renew.log"
    hour: "{{ ubuntu_1604_letsencrypt_apache_auto_renew_hour }}"
    minute: "{{ ubuntu_1604_letsencrypt_apache_auto_renew_minute }}"
