# tasks file for ubuntu-1604-letsencrypt-apache
---
- name: install (latest) | dependencies
  get_url:
    url: "https://dl.eff.org/certbot-auto"
    dest: "/usr/local/bin/certbot-auto"
    force: true
    owner: root
    group: root
    mode: 0755
